### ISSUE TITLE
FE[Pages] - Tasting

### ISSUE THREAD

**Issue by krab7191** [krab7191/Run-Amok-Free#6]
- [x] API GET request to get current bevs
- [x] Display a card with a textarea for notes for each bev
- [x] API POST requests to submit the notes

**Comment by krab7191** [comment]
Employee (tasting notes page)
- [ ] API GET request to get current bevs
- [ ] Display a card with a textarea for notes for each bev
- [ ] API POST requests to submit the notes

**Comment by ocskier** [comment]
I put the comment text area in
